
DROP DATABASE BANK ;

-- Create a database name as bank 
-- Create schema name a hdfc  , axis , icic 

CREATE DATABASE  BANK ;


CREATE DATABASE  BANK_DEV ;

CREATE SCHEMA BANK_DEV.HDFC ;


CREATE SCHEMA BANK_DEV.AXIS ;


CREATE SCHEMA BANK_DEV.MORGAN ;


CREATE OR REPLACE TABLE  BANK_DEV.HDFC.EMP (
    EMPLOYEE_ID INT,
    FIRST_NAME  STRING,
    LAST_NAME STRING
) ;

SELECT * FROM BANK_DEV.HDFC.EMP ;

DESC TABLE BANK_DEV.HDFC.EMP ;

INSERT INTO BANK_DEV.HDFC.EMP (EMPLOYEE_ID, FIRST_NAME, LAST_NAME)
VALUES
    (1, 'John', 'Smith'),
    (2, 'Jane', 'Doe'),
    (3, 'Michael', 'Johnson'),
    (4, 'Emily', 'Williams'),
    (5, 'David', 'Brown');


----I NEED ADD ONE MORE COLUMN TO EMP TABLE AS ADDRESS 


CREATE OR REPLACE TABLE  BANK_DEV.HDFC.EMP (
    EMPLOYEE_ID INT,
    FIRST_NAME  STRING,
    LAST_NAME STRING ,
    ADDRESS STRING
) ;

ALTER TABLE BANK_DEV.HDFC.EMP 
 ADD ADDRESS STRING ;

ALTER TABLE BANK_DEV.HDFC.EMP 
 ADD PHONE STRING ;


ALTER TABLE BANK_DEV.HDFC.EMP
 DROP COLUMN PHONE;
 
SELECT * FROM BANK_DEV.HDFC.EMP ;


UPDATE BANK_DEV.HDFC.EMP  
    SET ADDRESS = 'blr' ;

 
UPDATE BANK_DEV.HDFC.EMP  
    SET ADDRESS = 'HYD' 
    WHERE EMPLOYEE_ID = 1 ;


    UPDATE BANK_DEV.HDFC.EMP  
    SET ADDRESS = 'chn' 
    WHERE EMPLOYEE_ID IN (4,5) ;


    ----DROP /DELETE / TRUNCATE 

  --dELETE  --  IF USER WANT TO DELETE SPECIFIC RECORDS OR ENTIRE TABLE RECORDS   

SELECT * FROM BANK_DEV.HDFC.EMP ;

DELETE FROM BANK_DEV.HDFC.EMP  ;


DELETE FROM BANK_DEV.HDFC.EMP  
     WHERE EMPLOYEE_ID IN ( 1,3) ;


TRUNCATE TABLE  BANK_DEV.HDFC.EMP  ;


DROP TABLE  BANK_DEV.HDFC.EMP ;   -- 1M   


UNDROP TABLE BANK_DEV.HDFC.EMP;





