





--url='s3://bucketsnowflakes3'

CREATE OR REPLACE DATABASE OUR_FIRST_DB;

CREATE OR REPLACE STAGE OUR_FIRST_DB.PUBLIC.BULK_LOAD_STAGE
    URL = 's3://bucketsnowflakes3'
    FILE_FORMAT = (TYPE = 'CSV' SKIP_HEADER = 1);

list @OUR_FIRST_DB.PUBLIC.BULK_LOAD_STAGE;


CREATE OR REPLACE TABLE OUR_FIRST_DB.PUBLIC.ORDERS (
    ORDER_ID VARCHAR(30),
    AMOUNT INT,
    PROFIT INT,
    QUANTITY INT,
    CATEGORY VARCHAR(30),
    SUBCATEGORY VARCHAR(30));

COPY INTO OUR_FIRST_DB.PUBLIC.ORDERS
    FROM @OUR_FIRST_DB.PUBLIC.BULK_LOAD_STAGE
    FILES = ('OrderDetails.csv') ;
  ---  PATTERN = '.*[.]csv' ;


COPY INTO OUR_FIRST_DB.PUBLIC.ORDERS
    FROM @OUR_FIRST_DB.PUBLIC.BULK_LOAD_STAGE
    PATTERN = '.*Order.*[.]csv' 
   -- VALIDATION_MODE = RETURN_5_ROWS ;

select * from OUR_FIRST_DB.PUBLIC.ORDERS;


---------------------------------------

CREATE OR REPLACE STAGE OUR_FIRST_DB.PUBLIC.BULK_LOAD_int_STAGE
    FILE_FORMAT = (TYPE = 'CSV' SKIP_HEADER = 1);


list @OUR_FIRST_DB.PUBLIC.BULK_LOAD_int_STAGE;


CREATE OR REPLACE TABLE OUR_FIRST_DB.PUBLIC.ORDERS_v1 (
    ORDER_ID VARCHAR(30),
    AMOUNT INT,
    PROFIT INT,
    QUANTITY INT,
    CATEGORY VARCHAR(30),
    SUBCATEGORY VARCHAR(30));




    COPY INTO OUR_FIRST_DB.PUBLIC.ORDERS_v1
    FROM @OUR_FIRST_DB.PUBLIC.BULK_LOAD_int_STAGE 
    PURGE=TRUE ;
    


    select * from OUR_FIRST_DB.PUBLIC.ORDERS_v1;



-------------------------------

---url='s3://snowflakebucket-copyoption/size/';
--urls =   url='s3://snowflakebucket-copyoption/returnfailed/';


CREATE OR REPLACE STAGE OUR_FIRST_DB.PUBLIC.orders_stage 
    URL = 's3://snowflakebucket-copyoption/returnfailed/'
    FILE_FORMAT = (TYPE = 'CSV' SKIP_HEADER = 1);

list @OUR_FIRST_DB.PUBLIC.orders_stage ;





  CREATE OR REPLACE TABLE OUR_FIRST_DB.PUBLIC.ORDERS (
    ORDER_ID VARCHAR(30),
    AMOUNT INT,
    PROFIT INT,
    QUANTITY INT,
    CATEGORY VARCHAR(30),
    SUBCATEGORY VARCHAR(30));  


select * from OUR_FIRST_DB.PUBLIC.ORDERS ;


COPY INTO OUR_FIRST_DB.PUBLIC.ORDERS
FROM @OUR_FIRST_DB.PUBLIC.orders_stage 
PATTERN = '.*Order.*[.]csv' 
ON_ERROR = 'CONTINUE'



COPY INTO OUR_FIRST_DB.PUBLIC.ORDERS
FROM @OUR_FIRST_DB.PUBLIC.orders_stage 
PATTERN = '.*Order.*[.]csv' 
ON_ERROR = 'SKIP_FILE'



COPY INTO OUR_FIRST_DB.PUBLIC.ORDERS
FROM @OUR_FIRST_DB.PUBLIC.orders_stage 
PATTERN = '.*Order.*[.]csv' 
ON_ERROR = 'CONTINUE'
FORCE=TRUE 


  CREATE OR REPLACE TABLE OUR_FIRST_DB.PUBLIC.ORDERS_V3 (
    ORDER_ID VARCHAR(30),
    AMOUNT INT,
    PROFIT INT,
    QUANTITY INT,
    CATEGORY VARCHAR(3),   ---30 CHARS 
    SUBCATEGORY VARCHAR(30));  


COPY INTO OUR_FIRST_DB.PUBLIC.ORDERS_V3
FROM @OUR_FIRST_DB.PUBLIC.orders_stage 
PATTERN = '.*Order.*[.]csv' 
ON_ERROR = 'CONTINUE'
TRUNCATECOLUMNS = TRUE 


SELECT * FROM OUR_FIRST_DB.PUBLIC.ORDERS_V3;


  CREATE OR REPLACE TABLE OUR_FIRST_DB.PUBLIC.ORDERS_V4 (
    ORDER_ID VARCHAR(30),
    AMOUNT INT,
    PROFIT INT,
    QUANTITY INT,
    CATEGORY VARCHAR(30),   ---30 CHARS 
    SUBCATEGORY VARCHAR(30));  

COPY INTO OUR_FIRST_DB.PUBLIC.ORDERS_V4
FROM @OUR_FIRST_DB.PUBLIC.orders_stage 
PATTERN = '.*Order.*[.]csv' 
ON_ERROR= CONTINUE 


SELECT * FROM OUR_FIRST_DB.PUBLIC.ORDERS_V4;


COPY INTO OUR_FIRST_DB.PUBLIC.ORDERS_V4
FROM @OUR_FIRST_DB.PUBLIC.orders_stage 
PATTERN = '.*Order.*[.]csv' 
VALIDATION_MODE = RETURN_ERRORS ;


COPY INTO OUR_FIRST_DB.PUBLIC.ORDERS_V4
FROM @OUR_FIRST_DB.PUBLIC.orders_stage 
PATTERN = '.*Order.*[.]csv' 
VALIDATION_MODE = RETURN_10_ROWS ;





  CREATE OR REPLACE TABLE OUR_FIRST_DB.PUBLIC.ORDERS_V5 (
    ORDER_ID VARCHAR(30),
    AMOUNT INT,
    PROFIT INT,
    QUANTITY INT,
    CATEGORY VARCHAR(30),   ---30 CHARS 
    SUBCATEGORY VARCHAR(30));  


LIST @OUR_FIRST_DB.PUBLIC.orders_stage ;


COPY INTO OUR_FIRST_DB.PUBLIC.ORDERS_V5
FROM @OUR_FIRST_DB.PUBLIC.orders_stage 
PATTERN = '.*Order.*[.]csv' 
SIZE_LIMIT = 60000
ON_ERROR = CONTINUE



COPY INTO OUR_FIRST_DB.PUBLIC.ORDERS_V5
FROM @OUR_FIRST_DB.PUBLIC.orders_stage 
PATTERN = '.*Order.*[.]csv' 
SIZE_LIMIT = 30000
ON_ERROR = CONTINUE

size
--54622  --64 
--10514
--54597
--54598


COPY INTO OUR_FIRST_DB.PUBLIC.ORDERS_V5
FROM @OUR_FIRST_DB.PUBLIC.orders_stage 
PATTERN = '.*Order.*[.]csv' 
--SIZE_LIMIT = 30000
ON_ERROR = CONTINUE
PURGE=TRUE 

---PURGE WILL WORK FOR ONLY INTERNAL STAGE 